<?php

return [
    'rooms' => [
        'Manajemen' => [
            'Direktur',
            'Kepala TU',
            'Keuangan',
            'Umum dan Kepegawaian',
            'Rapat Kecil',
            'Rapat Besar',
            'Penagihan BPJS',
            'Pelayanan Medis (Yanmed)',
            'PKRS',
            'TI',
            'Ruang Server',
            'Lorong Manajemen',
            'Keperawatan',
            'Komite Medik',
            'SPI',
            'Koordinator Rawat Jalan',
            'Kasir',
            'MPP',
            'PPI',
            'Gudang Aset',
        ],

        'Rawat Jalan' => [
            'Anak',
            'Umum',
            'THT',
            'Gigi Umum',
            'Kulit',
            'Gizi',
            'Rekam Medis Lt. 1',
            'Rekam Medis Lt. 2',
            'Kandungan',
            'Dalam',
            'Saraf',
            'Loket Rawat Jalan',
            'Ruang Tunggu Rawat Jalan',
            'Loket Informasi dan Pengaduan',
            'Bedah Tulang',
            'Mata',
            'Bedah Umum',
            'VCT',
            'Jantung',
            'Jiwa',
            'Gigi Spesialis',
            'Okupasi Terapi',
            'Fisioterapi',
            'Hemodialisa',
        ],

        'Rawat Inap' => [
            'Bougenville',
            'ICU',
            'ICU 2',
            'Crisant',
            'Anggrek',
            'VK Bersalin',
            'Perinatologi',
            'Melati',
            'Flamboyan',
            'Dahlia',
            'Teratai',
            'Tulip',
        ],

        'IGD' => [
            'Loket Pendaftaran IGD',
            'Nurse Station IGD',
            'Admin IGD',
            'Kasir IGD',
            'Apotik IGD',
            'Nurse Station Ponek',
        ],

        'Penunjang' => [
            'Radiologi',
            'Laboratorium',
            'Bank Darah',
            'OK',
            'Admin OK',
            'Apotik Rawat Jalan',
            'Apotik Rawat Inap',
            'Gudang Apotik',
            'Apotik OK',
            'Endoscopy',
            'Kamar Jenazah',
            'Ambulance',
            'IPSRS',
            'Sanitasi',
            'Laundry',
            'CSSD',
        ],
    ],
    'categories' => [
        'Hardware'  => 'Hardware',
        'Software'  => 'Software',
        'Network'   => 'Network',
        'Sistem RS' => 'Sistem RS',
        'Pemeliharaan' => 'Pemeliharaan'
    ],
];
